services:
  kafka:
    image: apache/kafka:3.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: vietpase
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"

  inventory-db:
    image: postgres:15
    environment:
      POSTGRES_USER: vietpase
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: vietpase
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"