server:
  port: 8083
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: vietpase
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"